ARG ROS_DISTRO=humble
 
FROM osrf/ros:${ROS_DISTRO}-desktop as base
ENV ROS_DISTRO=${ROS_DISTRO}
SHELL ["/bin/bash", "-c"]
 
# Create Colcon workspace with external dependencies
RUN mkdir -p /mandeye_ws/src/
WORKDIR /mandeye_ws/
RUN cd ./src && git clone https://github.com/michalpelka/mandeye_to_bag.git  && cd mandeye_to_bag && git submodule init && git submodule update
    
RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && colcon build 

RUN apt-get update && apt-get install -y \
    python3-pip \
    unzip \
    p7zip-full &&\
    pip install gdown 

# SETUP SYSTEM UNDER TEST
ARG SYSTEM_SETUP=setup_kiss.sh
COPY $SYSTEM_SETUP system_setup.sh
RUN source ./install/setup.sh \
    && ./system_setup.sh

# copy system undertest
ARG SYSTEM_RUN=run_kiss.sh
COPY $SYSTEM_RUN system_run.sh


# copy datasets
COPY ./slams_dojo_datasets ./slams_dojo_datasets

# download data with given script
ARG DATASET=data_office
ENV DATASET_NAME=$DATASET
RUN cd ./slams_dojo_datasets  && ls
RUN ./slams_dojo_datasets/$DATASET.sh

# Clean up process artifacts
RUN rm -f /test_data_mandeye/*lio*.laz

# CONVERT DATA
RUN source ./install/setup.sh \
    && ros2 run mandeye_to_rosbag2 mandeye_to_rosbag2_node /test_data_mandeye /test_data_bag

RUN source ./install/setup.sh

