ARG ROS_DISTRO=noetic

FROM osrf/ros:${ROS_DISTRO}-desktop as base
ENV ROS_DISTRO=${ROS_DISTRO}
SHELL ["/bin/bash", "-c"]
 
RUN apt-get update && apt-get install -y \
    python3-pip \
    unzip \
    p7zip-full \
    git \
    python3-catkin-tools &&\
    pip install gdown vcstool

RUN mkdir -p /mandeye_ws/src/
WORKDIR /mandeye_ws/
RUN cd /mandeye_ws/src/ && git clone https://github.com/michalpelka/mandeye_to_bag.git\
    && cd mandeye_to_bag && git submodule init && git submodule update

RUN cd / && git clone https://github.com/Livox-SDK/Livox-SDK.git && cd Livox-SDK \
    && mkdir -p build && cd build \
    && cmake .. && make && make install

RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && cd /mandeye_ws/src \
    && vcs import --input mandeye_to_bag/mandeye_to_rosbag1/livox.repos

RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && cd /mandeye_ws/ \
    && rosdep update && rosdep install --from-paths src --ignore-src -r -y

RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && cd /mandeye_ws/ \
    && rm -r src/mandeye_to_bag/mandeye_to_rosbag2/ \
    && catkin_make 

# Build FAST_LIO
RUN cd /mandeye_ws/src \
    && git clone https://github.com/hku-mars/FAST_LIO.git \
    && cd FAST_LIO \
    && git submodule init && git submodule update

RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && cd /mandeye_ws/ \
    && catkin_make 

# copy datasets
COPY ./slams_dojo_datasets ./slams_dojo_datasets

# download data with given script
ARG DATASET=data_office
ENV DATASET_NAME=$DATASET
RUN cd ./slams_dojo_datasets  && ls
RUN ./slams_dojo_datasets/$DATASET.sh

# Clean up process artifacts
RUN rm /test_data_mandeye/*lio*.laz

# # CONVERT DATA
RUN source /mandeye_ws/devel/setup.sh \
    && rosrun mandeye_to_rosbag1 mandeye_to_rosbag /test_data_mandeye /test_data_bag

# copy system undertest
ARG SYSTEM_RUN=run_fastlio.sh
COPY $SYSTEM_RUN system_run.sh

RUN source /mandeye_ws/devel/setup.sh